# name: Check
# on: push
# jobs:
#   lint:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@7
#       - name: Install deps
#         run: npm ci
#       - name: Test
#         run: npm run lint
#   test:
#     needs: [lint]
#     runs-on: windows-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@7
#       - name: Install deps
#         run: npm ci
#       - name: Test
#         run: npm run test
